# Generated by Django 5.2.8 on 2025-12-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_reaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction",
            old_name="user",
            new_name="author",
        ),
    ]
